version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # to ensure they are valid docker tag names (used in build pipeline)
      separator: "-"
    # Specify labels for npm pull requests
    labels:
      - "release-patch"
      - "dependencies"
